version: '3'
services:
 mongodb:
   image: mongo
   ports:
     - "27017:27017"
   container_name: mongo2
   network_mode: host
 muzixapp:
   image: trackservice
   build: userservice/
   restart: always
   container_name: trackservice2
   network_mode: host
   ports:
     - "8090:8090"
   expose:
     - 8090
 configservice:
   image: configservice
   build: configservice/
   restart: always
   container_name: configservice2
   network_mode: host
   ports:
     - "8082:8082"
   expose:
     - 8082
 zuul:
   image: zuul
   build: zuulservice/
   restart: always
   container_name: zuulservice2
   network_mode: host
   ports:
     - "8081:8081"
   expose:
     - 8081
 eureka:
   image: eurekaserver
   build: eurekaservice/
   restart: always
   container_name: eurekaservice2
   network_mode: host
   ports:
     - "8761:8761"
   expose:
     - 8761
